name: libroguelike

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - run:   |
            sudo apt update
            sudo apt install gcc g++ clang
     shell: bash
   - name: checkout repo
     uses: actions/checkout@main
   - name: build application with GCC
     run: make -B
   - name: build application with clang
     run: make -B CC=clang
