name: libroguelike

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - run:   |
            sudo apt update
            sudo apt install -y build-essential gcc clang cc65
     shell: bash
   - name: checkout repo
     uses: actions/checkout@main
   - name: build application with default compiler (GCC)
     run: make -B
   - name: build application with clang
     run: make -B CC=clang
   - name: build application with cc65 (commodore 64 compiler)
     run: cl65 -DRL_ENABLE_FOV=0 -DRL_MAPGEN_BSP_RANDOMISE_ROOM_LOC=0 examples/c89.c
     shell: bash
